//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compartido.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Camisetas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Camisetas()
        {
            this.DetallesFactura = new HashSet<DetallesFactura>();
            this.TallasCamiseta = new HashSet<TallasCamiseta>();
        }
    
        public int Id { get; set; }
        public string NombreEquipo { get; set; }
        public int LigaId { get; set; }
    
        public virtual Ligas Ligas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesFactura> DetallesFactura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TallasCamiseta> TallasCamiseta { get; set; }
    }
}
