//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compartido.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.DetallesFactura = new HashSet<DetalleFactura>();
        }
    
        public System.DateTime FechaCreacion { get; set; }
        public int ClienteId { get; set; }
        public double Total { get; set; }
        public Nullable<int> VendedorId { get; set; }
        public int Id { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Empleado Vendedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFactura> DetallesFactura { get; set; }
    }
}
