//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compartido.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entidades : DbContext
    {
        public Entidades()
            : base("name=Entidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Camiseta> Camisetas { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Empleado> Empleados { get; set; }
        public virtual DbSet<Factura> Facturas { get; set; }
        public virtual DbSet<Genero> Generos { get; set; }
        public virtual DbSet<Liga> Ligas { get; set; }
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<Rol> Roles { get; set; }
        public virtual DbSet<Talla> Tallas { get; set; }
        public virtual DbSet<TipoDeDocumento> TiposDeDocumento { get; set; }
        public virtual DbSet<DetalleFactura> DetallesFactura { get; set; }
        public virtual DbSet<Pago> Pagos { get; set; }
        public virtual DbSet<TallaCamiseta> TallasCamiseta { get; set; }
        public virtual DbSet<TallaGenero> TallasGenero { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
