//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compartido.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entidades : DbContext
    {
        public Entidades()
            : base("name=Entidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Camisetas> Camisetas { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<Facturas> Facturas { get; set; }
        public virtual DbSet<Generos> Generos { get; set; }
        public virtual DbSet<Ligas> Ligas { get; set; }
        public virtual DbSet<Personas> Personas { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Tallas> Tallas { get; set; }
        public virtual DbSet<TiposDeDocumento> TiposDeDocumento { get; set; }
        public virtual DbSet<DetallesFactura> DetallesFactura { get; set; }
        public virtual DbSet<Pagos> Pagos { get; set; }
        public virtual DbSet<TallasCamiseta> TallasCamiseta { get; set; }
        public virtual DbSet<TallasGenero> TallasGenero { get; set; }
    }
}
