//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compartido.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        public int EmpleadoId { get; set; }
        public System.DateTime FechaPago { get; set; }
        public double Sueldo { get; set; }
    
        public virtual Empleados Empleados { get; set; }
    }
}
